# Generated by Django 4.2.5 on 2023-09-08 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=1000)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=100000)),
                ('blog_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='blog.blogauthor')),
            ],
        ),
    ]
