# Generated by Django 4.2.5 on 2023-09-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='last_name',
            field=models.CharField(default='value', max_length=100),
            preserve_default=False,
        ),
    ]
